import {generateurHTML, generateurCodeHTML, generateurCodeJS} from '../../../lib/generateHTML';

export default {
	idArticle				:	state => state.idArticle,
	meta_title 				:	state => state.article.meta_title,
	meta_description 		:	state => state.article.meta_description,
	title 					:	state => state.article.title,
	slug 					:	state => state.article.slug,
	description 			:	state => { console.log("get active"); return state.article.description},
	categorie 				:	state => state.article.categorie,
	auteur 					:	state => state.article.auteur,
	tags 					:	state => state.article.tags,
	img_catego 				:	state => state.article.img_catego,
	fa_image 				:	state => state.article.fa_image,
	fa_title 				:	state => state.article.fa_title,
	fa_description 			:	state => state.article.fa_description,
	contenu					:	state => state.article.contenu,
	contenuByIndex 			:	state => index => state.article.contenu[index],
	count 					:	state => state.count,
	categories 				:	state => state.categories,
	auteurs 				:	state => state.auteurs,
	jsonArticle 			:	state => JSON.stringify(state.article),
	erreur_meta_title 		:	state => state.erreurs.meta_title,
	erreur_meta_description :	state => state.erreurs.meta_description,
	erreur_title 			:	state => state.erreurs.title,
	erreur_slug 			:	state => state.erreurs.slug,
	erreur_description 		:	state => state.erreurs.description,
	erreur_categorie 		:	state => state.erreurs.categorie,
	erreur_auteur 			:	state => state.erreurs.auteur,
	erreur_tags 			:	state => state.erreurs.tags,
	erreur_img_catego 		:	state => state.erreurs.img_catego,
	erreur_fa_image 		:	state => state.erreurs.fa_image,
	erreur_fa_title 		:	state => state.erreurs.fa_title,
	erreur_fa_description 	:	state => state.erreurs.fa_description,
	erreur_contenu 			:	state => state.erreurs.contenu,
	load_img_catego 		:	state => state.load.img_catego,
	load_fa_image 			:	state => state.load.fa_image,
	output_html             :   state => generateurHTML(state.article.contenu),
	output_src              :   state => generateurCodeHTML(state.article.contenu),
	output_jsonArticle      :   (state, getters, rootState) => generateurCodeJS(JSON.stringify(state)),
	montest		: 	state => "ok"
}